2024-06-22 22:11:52,100 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Current SDK version is 0.17.2
2024-06-22 22:11:52,100 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Configure stats pid to 24824
2024-06-22 22:11:52,100 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Loading settings from C:\Users\30533\.config\wandb\settings
2024-06-22 22:11:52,100 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Loading settings from C:\Users\30533\Desktop\Pytorch-UNet-master\wandb\settings
2024-06-22 22:11:52,100 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-22 22:11:52,100 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': 'c:\\Users\\30533\\Desktop\\Pytorch-UNet-master\\train.py', 'program': 'c:/Users/30533/Desktop/Pytorch-UNet-master/train.py'}
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_setup.py:_flush():76] Applying login settings: {'anonymous': 'must'}
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_init.py:_log_setup():520] Logging user logs to C:\Users\30533\Desktop\Pytorch-UNet-master\wandb\run-20240622_221152-mnlyxf53\logs\debug.log
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_init.py:_log_setup():521] Logging internal logs to C:\Users\30533\Desktop\Pytorch-UNet-master\wandb\run-20240622_221152-mnlyxf53\logs\debug-internal.log
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_init.py:init():560] calling init triggers
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_init.py:init():610] starting backend
2024-06-22 22:11:52,101 INFO    MainThread:24824 [wandb_init.py:init():614] setting up manager
2024-06-22 22:11:52,103 INFO    MainThread:24824 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-06-22 22:11:52,106 INFO    MainThread:24824 [wandb_init.py:init():622] backend started and connected
2024-06-22 22:11:52,110 INFO    MainThread:24824 [wandb_init.py:init():711] updated telemetry
2024-06-22 22:11:52,113 INFO    MainThread:24824 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-22 22:13:22,961 ERROR   MainThread:24824 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-22 22:13:22,961 ERROR   MainThread:24824 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "D:\Anaconda3\envs\U-net\lib\site-packages\wandb\sdk\wandb_init.py", line 1171, in init
    return wi.init()
  File "D:\Anaconda3\envs\U-net\lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-22 22:13:25,633 WARNING MsgRouterThr:24824 [router.py:message_loop():77] message_loop has been closed
